### PR TITLE
fix alphabet translation using 1:1 dict and prefix

### PR DESCRIPTION
**Pull request by avivcarmis**

### CODE REVIEW

**Comment by avivcarmis** [comment]
Screen Shot 2021-01-04 at 20 08 55

**Comment by marmor7** [comment]
you can use diacritics to make things more readable, e.g.
"ש" = "š"
which is [actually pronounced "sh"](https://en.wikipedia.org/wiki/%C5%A0)

i'm sure we can find nice substitutes to all hebrew letters using diacritics in a way that keeps the hebrew names readable

**Comment by avivcarmis** [comment]
closing in favour of https://github.com/ChavaScript/chavascript/pull/36

**Pull request closed without merging**
