### PR TITLE
fix alphabet translation using hash function and prefix

### PR DESCRIPTION
**Pull request by avivcarmis**

### CODE REVIEW

**Comment by avivcarmis** [comment]
Screen Shot 2021-01-04 at 20 15 51

**Comment by avivcarmis** [comment]
hash function taken from [here](https://stackoverflow.com/a/7616484)

**Comment by dorilahav** [comment]
Would suggest to also use a dictionary because the hash is not very long.
There is a good chance that a whole project including some libraries would have more than 10000 functions and variables so it could actually have 2 functions with the same name.

**Comment by dorilahav** [comment]
A nice and clean solution might be to just create a counter and use it's value to name variables and functions.

**Comment by elisherer** [comment]
@dorilahav , it's important to stay deterministic, 
I think it would be a good idea to use both hash and transliteration for readability sake.
```js
function $chava_46165799_lbrch($chava_1432970484_mbvrch) {
    console.log('היוש, ' + $chava_1432970484_mbvrch);
}
$chava_46165799_lbrch('עולם');
```
WDYT?

**Comment by avivcarmis** [comment]
> @dorilahav , it's important to stay deterministic,
> I think it would be a good idea to use both hash and transliteration for readability sake.
> 
> ```js
> function $chava_46165799_lbrch($chava_1432970484_mbvrch) {
>     console.log('היוש, ' + $chava_1432970484_mbvrch);
> }
> $chava_46165799_lbrch('עולם');
> ```
> 
> WDYT?

I agree

**Comment by avivcarmis** [comment]
@dorilahav I do agree with @elisherer that we want determinism. I also agree that we want to avoid collisions of hash result. I think that a combination of the two should be safe enough for the purposes of חווה סקריפט.
closing in favour of https://github.com/ChavaScript/chavascript/pull/36

**Pull request closed without merging**
